package com.RegularExprrssions;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class CharacterClasses {

    public static void main(String[] args) {
        int count=0;
        Pattern p = Pattern.compile("chintu");
        Matcher m = p.matcher("chintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjchintulsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadvvchintusanflkdsfnskjdafkjlsalfkjsdakjbfjakbfjklsabdklfasdlflsadvchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsadchintusanflkdsfnskjdafkjlsalfkjsdakjbfjsdakbfjklsabdklfasdlflsad");

        while (m.find()){
            count++;
            System.out.println(m.start()+".."+m.group());
        }
        System.out.println(count);
    }
}
